### ISSUE TITLE
Autotune -> Save to Basals ... Zero's Basals

### ISSUE THREAD

**Issue by scrappy** [Artificial-Pancreas/iAPS#711] opened 2024-05-25 04:32 UTC
Just recording this ... David / Heather on Slack just found this:

Record your basal schedule before you do this. To reproduce… [Settings][Autotune][Run Now], choose [Save as your normal Basal rates], confirm [Yes], your saved basal rates are all now 0!

**Comment by Jon-b-m** [comment] 2024-05-25 11:02
Do you have screenshots of your AT basals?

**Comment by scrappy** [comment] 2024-05-25 17:59
Sadly, 'Save to ...' doesn't even work on my phone, running dev ... my before and after basal rates are the same, even though I did tap 'Yes' when prompted ...

AT vs Basals:

![IMG_6494](https://github.com/Artificial-Pancreas/iAPS/assets/609712/2ce5fd68-7f8e-497c-a9f0-bcdad2c80a46)
![IMG_6493](https://github.com/Artificial-Pancreas/iAPS/assets/609712/46c20c28-0805-4090-98ff-2d1bb2bf6a39)

**Comment by darrelld3** [comment] 2024-05-25 21:06
I just ran a test and get the same zero basal on save. The recommended values look good but after hitting save everything saved to the pod is zero.  AT recommended[A screenshot of a phone  Description automatically generated]

After selecting “Save as your normal basal rates” the basal profile looks like this, all the AT
rates get zeroed.
[A screenshot of a phone  Description automatically generated]

From: Marc G. Fournier ***@***.***>
Date: Saturday, May 25, 2024 at 12:59 PM
To: Artificial-Pancreas/iAPS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [Artificial-Pancreas/iAPS] Autotune -> Save to Basals ... Zero's Basals (Issue #711)

Sadly, 'Save to ...' doesn't even work on my phone, running dev ... my before and after basal rates are the same, even though I did tap 'Yes' when prompted ...

AT vs Basals:

IMG_6494.PNG (view on web)<https://github.com/Artificial-Pancreas/iAPS/assets/609712/2ce5fd68-7f8e-497c-a9f0-bcdad2c80a46>
IMG_6493.PNG (view on web)<https://github.com/Artificial-Pancreas/iAPS/assets/609712/46c20c28-0805-4090-98ff-2d1bb2bf6a39>

**Comment by Jon-b-m** [comment] 2024-05-29 12:43
Im not sure yet why this is suddenly not working anymore. I’ll probably disable the save AT until this has been fixed.

**Comment by Jon-b-m** [comment] 2024-05-29 13:05
Disabled in latest dev

**Comment by drspike** [comment] 2024-06-06 23:14
I believe the issue is AT is recommending basals that aren’t multiples of 0.05. Ie a basal of 1.33 instead of 1.30. Omnipod delivers basals via 0.05 increments and so the basals saved from AT are listed as 0.0 in my basal profile if I save the basals from AT.  If I check the Debug menu “Basal Profile” then the basal rates are saved from AT but they are intervals of 0.01 instead of 0.05. The basals still work it’s just the Basal Profile menu can’t display basals that don’t end in 0.00 or 0.05.

**Comment by drspike** [comment] 2024-06-06 23:20
![IMG_2683](https://github.com/Artificial-Pancreas/iAPS/assets/16395887/e7d25fe4-bfc9-431e-bf45-41fd2f548f3a)


Not sure if 722 for model variable matters but I am using Dash pods.

**Comment by Jon-b-m** [comment] 2024-11-24 23:43
Resolved in dev branch

**Closed by Jon-b-m** 2024-11-24 23:43 UTC
Labels: Already Implemented in Dev
