### ISSUE TITLE
Possible rounding issue in glucose values

### ISSUE THREAD

**Issue by dsut4392** [Artificial-Pancreas/iAPS#398] opened 2023-11-30 06:02 UTC
I’m seeing an occasional small discrepancy between Dexcom glucose values in the main display and the History display. Main screen reported value matches what is seen in the G6 app.  Smooth Glucose Value is turned OFF in the CGM settings. 
iAPS dev 2.2.9 branch 1079fb7
Dexcom G6 mmol/L
iOS 16.7.1, iPhone 12mini

![IMG_4061](https://github.com/Artificial-Pancreas/iAPS/assets/55490253/282383e6-40f7-4e10-8cdf-34caa0d83dc0)
![IMG_4060](https://github.com/Artificial-Pancreas/iAPS/assets/55490253/84039a20-7317-4a31-80a7-48c2cbd45307)

**Comment by dnzxy** [comment] 2023-12-02 15:03
@dsut4392 exceptional find, great eye for detail! While I could not reproduce this issue in a simulator, I did find that glucose in history uses a different rounding method than basically *anywhere else* in the app. I've adjusted it to be consistent. If you could maybe check that out (PR #408 to `alpha`) and report back?

**Comment by Jon-b-m** [comment] 2023-12-09 12:18
Fixed in dev

**Closed by Jon-b-m** 2023-12-09 12:18 UTC
Labels: bug
